# Use https://dependabot.com/docs/config-file/validator/ to check for errors.
version: 2
updates:
  # Enable version updates for Actions
  - package-ecosystem: "github-actions"
    # Look for `.github/workflows` in the `root` directory
    directory: "/"
    schedule:
      interval: "weekly"
